---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloud-provider-secret
  namespace: kube-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secrets
  target:
    name: cloud-provider-secret
    template:
      engineVersion: v2
      data:
        application_credential_id: '{{ .applicationCredentialId }}'
        application_credential_secret: '{{ .applicationCredentialSecret }}'
  data:
    - secretKey: applicationCredentialId
      remoteRef:
        key: cluster-secrets
        property: application_credential_id
    - secretKey: applicationCredentialSecret
      remoteRef:
        key: cluster-secrets
        property: application_credential_secret
