apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/kubermatic/machine-controller/refs/tags/v1.65.0/examples/machine-controller.yaml
  - cloud-provider-secret.yaml

images:
  - name: quay.io/kubermatic/machine-controller
    newTag: v1.65.0

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: machine-controller-webhook
        namespace: kube-system
      spec:
        template:
          spec:
            containers:
              - name: webhook
                args:
                  - -log-debug
                  - -log-format=console
                  - -listen-address=0.0.0.0:9876
                  - -namespace=kube-system
                  - -node-external-cloud-provider
                  - -tls-cert-path=/tmp/cert/tls.crt
                  - -tls-key-path=/tmp/cert/tls.key
                command:
                  - /usr/local/bin/webhook
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: machine-controller
        namespace: kube-system
      spec:
        template:
          spec:
            containers:
              - name: machine-controller
                args:
                  - -health-probe-address=0.0.0.0:8085
                  - -metrics-address=0.0.0.0:8080
                  - -node-csr-approver
                  - -node-external-cloud-provider
                  - -join-cluster-timeout=15m
                command:
                  - /usr/local/bin/machine-controller
                env:
                  - name: OS_APPLICATION_CREDENTIAL_ID
                    valueFrom:
                      secretKeyRef:
                        name: cloud-provider-secret
                        key: application_credential_id
                  - name: OS_APPLICATION_CREDENTIAL_SECRET
                    valueFrom:
                      secretKeyRef:
                        name: cloud-provider-secret
                        key: application_credential_secret
