apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: cluster-autoscaler
    repo: https://kubernetes.github.io/autoscaler
    version: 9.53.0
    releaseName: cluster-autoscaler
    namespace: kube-system
    valuesFile: values.yaml

patches:
  - target:
      group: rbac.authorization.k8s.io
      kind: ClusterRole
      name: cluster-autoscaler
    patch: |-
      - op: add
        path: /rules/-
        value:
          apiGroups:
            - cluster.k8s.io
          resources:
            - machinedeployments
            - machinepools
            - machines
            - machinesets
          verbs:
            - get
            - list
            - update
            - watch
      - op: add
        path: /rules/-
        value:
          apiGroups:
            - cluster.k8s.io
          resources:
            - machinedeployments/scale
            - machinepools/scale
          verbs:
            - get
            - patch
            - update
